# Generated by Django 5.2.10 on 2026-01-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_timelineentry_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='timelineentry',
            new_name='timeline_ti_event_i_22119c_idx',
            old_name='timeline_entry_event_created_idx',
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='type',
            field=models.CharField(choices=[('event_status', 'Event status change'), ('task_created', 'Task created'), ('task_updated', 'Task updated'), ('task_completed', 'Task completed'), ('budget_item_created', 'Budget item created'), ('budget_item_updated', 'Budget item updated'), ('budget_item_deleted', 'Budget item deleted'), ('automation', 'Automation trigger'), ('automation_rule', 'Automation rule action'), ('certificate_generated', 'Certificate generated'), ('certificate_batch_submitted', 'Certificate batch submitted'), ('certificate_batch_completed', 'Certificate batch completed'), ('certificate_batch_failed', 'Certificate batch failed'), ('chat_system', 'Chat system message'), ('file_uploaded', 'File uploaded'), ('poster_edit', 'Poster edit/lock'), ('user_joined', 'User joined'), ('user_left', 'User left'), ('ai_query', 'AI assistant query'), ('ai_response', 'AI assistant response')], max_length=64),
        ),
    ]
