# Generated by Django 5.2.6 on 2026-02-07 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_add_budget_indexes'),
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['room', '-created_at'], name='files_filea_room_id_26a8d7_idx'),
        ),
    ]
