# Generated by Django 5.2.6 on 2025-09-20 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_messageread'),
        ('events', '0001_initial'),
        ('poster', '0002_posterdraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='posterdraft',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='posterdraft',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posterdraft',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posterdraft',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poster_drafts', to='chats.chatroom'),
        ),
        migrations.AlterField(
            model_name='posterdraft',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poster_drafts', to='events.event'),
        ),
        migrations.AlterField(
            model_name='posterdraft',
            name='name',
            field=models.CharField(default='Untitled', max_length=200),
        ),
        migrations.AlterField(
            model_name='posterdraft',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posterdraft',
            name='state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
