# Generated by Copilot to align CertificateRecord with event-aware workflow
from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    CertificateRecord = apps.get_model('poster', 'CertificateRecord')
    # Preserve existing recipient_name into name when present
    for rec in CertificateRecord.objects.all():
        if hasattr(rec, 'recipient_name') and rec.recipient_name:
            rec.name = rec.recipient_name
            rec.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0005_merge_0004_alter_template_owner_0002_extend_certificates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificaterecord',
            old_name='recipient_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='certificaterecord',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='certificaterecord',
            name='source_filename',
        ),
        migrations.RemoveField(
            model_name='certificaterecord',
            name='status',
        ),
        migrations.RemoveField(
            model_name='certificaterecord',
            name='meta',
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='certificaterecord',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_records', to='events.event'),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
