# Generated by Django 5.2.6 on 2025-09-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chatroom_created_by_chatmembership_chatroom_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_flag',
            field=models.BooleanField(default=False),
        ),
    ]
