# Generated by Django 5.2.6 on 2025-09-19 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('chats', '0002_chatroom_created_by_chatmembership_chatroom_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='chats.chatroom'),
        ),
    ]
