# Generated by Django 5.2.6 on 2026-02-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_merge_0002_budgethealth_0002_budgetitem_room'),
        ('chats', '0005_add_budget_indexes'),
        ('events', '0003_merge_0002_event_participants_0002_event_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['event', 'type'], name='budget_budg_event_i_089cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['event', '-created_at'], name='budget_budg_event_i_34a8e6_idx'),
        ),
    ]
